language: python
python:
  - '3.5'
  - '3.6'
sudo: required
service:
  - docker
before_install:
  - docker-compose up -d
install:
  - pip3 install -r requirements.txt
script:
  - python3 -m flake8
  - python -m pytest --cov=. --cov-fail-under=69 --cov-report=term-missing:skip-covered
  - coveralls
