sudo: required
language: python
cache: pip
python:
- '3.6'
service:
- docker
notifications:
  slack:
    secure: imXU/zt9IjKk5OvjZkTICTmxOTKGaZIej2kf7m5iSAKrdM7Lsjhj1m464qOViH3AMjMMZeprC1SL/jFF5azu2DNkQe5j1UlUu1ZxQpwnpmXJaLyTznDZSa76LPoY/R4sqJYozZLzfMQivnIUe6NGTP5vDX8CXpndaOgfAulDzks6xXDTw8q1dyKTtqFx8aPbAFAYRPagaNpy62j09aeNXDY8OVUSJsx8xylRmbHY+t1AH5AMkDPY5AeI0D/CJH1Hnbq88MmvdgUn8OqjvWMgiXsrDFAPZ4WdZCgJZuP2D4jrDuAsnchrOrVi6wKJWA9rNqJD8TqqF8Q8JhdeVAJ098GXAyhkJlDtfeEbh8TYIkLNgpW7e/auh5rzHk5MvH7kTVzyZjGMb7Vo+7c7nypFoWeom1m8Pg5rCT7vx7+0NhQjg1moMQ2kPWzaZkITDdblxuf6rpraEx2ydqPh6pAAto+VWXRrdbJJTGSTVIfPFDHYeqkCq+QVGfdCi2BucnnQVZJLUqEdGxnn86ICwhjJ5uC4Ah7Czd/pZOrdgFMWTT6DS9fjRiIHOnAAp1wKYzAoRBKQkhltDFMrayDxN5dp+IXDnnlQWPm14mwAyNd/zt8pWCue5hT2oK7oeuQsNfSemSPg92DCZRZNZ684UbJGKn0RJlSpXLyQRjja0IjA+Kk=
    on_success: change
    on_failure: change
    on_pull_requests: false
stages:
- name: test
- name: publish
  if: tag =~ ^v.*
- name: verify
  if: branch = master AND type = push
jobs:
  include:
  - stage: test
    before_install:
    - docker-compose -f docker-compose.yml -f docker-compose.kubernetes.yml up -d
    install:
    - pip3 install -r requirements.txt
    script:
    - python3 -m flake8
    - python3 -m pytest --cov=. --cov-report=term-missing:skip-covered
    - coveralls
    - pip3 install --editable .
    - python3 -m kqueen &
    - sleep 2
    - wget -O - http://localhost:5000/api/v1/health
  - stage: publish
    script:
    - "/bin/true"
    deploy:
      provider: pypi
      user: tomkukral
      password:
        secure: Xfov5rO0PH40sBITF8TxfbnMJcRD9DZ5Bl1JNBwsk+dd56dpZUR5ZMAmjjGgMQTMk6JPfU1EDx/c4r8SS5gU3LErPI9cuHzggp59hhAMIjKdI7a42t6vLPc/fmymWBejhhcA2NAgDzc7p6B50ZiFJGchWADrvuVpDhzQIrokayv83FnKcB4cY31LKLJwu85o5CehUMQCRlvzCv/NuEstfJEdIhqzx2xnQI8qlLPNtMHtCJy5r/kauURFpx2IqgQ2WjMVWsfAtSlT+b5n7rZrhPCrCWD4C1VGWK5+LpxcuEhVb33oeaT1y2wpSo5+rg4c12/HP/HQXYPe0HoHJxKshT3Xw5YjcwQtoYpvkrmssHbEzY0l1QBkRqFVnuybXMcqLW2YSoUJ2M62U1ll0TyvFl/R9j1Jf+tXFxwANr+buaWSPW/FBsfMw//+EBXmNGAmwT+VfPdEysGP95bM1Ewl4w2OHLj1IDvA/V1d/Uf1NXOr0A8Q4MeiDT+PFngwoK+QKdVPO0hoErKJZ1QXXEALdBEbnuDM60a8gvJCD7D5sfygfUCVRxSvcQfFRULam5JvHcyH7JeWJzlBabKl9YNJbQgji1vkbLk1gEyyKl7SayLGngqVzdrCCLlfRbH8UsPR8pgIWW4LU5DS3AsWz3ln6mfyHV333DDj4r9ImZDMvhI=
      on:
        tags: true
        repo: Mirantis/kqueen
  - stage: verify
    before_install:
    - docker-compose -f docker-compose.yml -f docker-compose.kubernetes.yml up -d
    install:
    - pip3 install --upgrade kqueen
    script:
    - "./entrypoint.sh &"
    - sleep 2
    - wget -O - http://localhost:5000/api/v1/health
