swagger: "2.0"

info:
  version: "0.1"
  title: Kubernetes Queen API
  description: A simple API to interact with Kubernetes clusters

schemes:
  - https
  - http

basePath: /api/v1

definitions:
  Cluster:
    type: object
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
      provisioner:
        type: "string"
      state:
        type: "string"
        enum:
          - "deployed"
          - "failed"
          - "deleted"
  ClusterNode:
    type: object
    properties:
      name:
        type: string
      # TODO: more properties
  ClusterService:
    type: object
    properties:
      name:
        type: string
      # TODO: more properties

paths:
  # clusters
  /clusters:
    get:
      summary: List all clusters
      responses:
        200:
          description: "Successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Cluster"

  /clusters/{id}:
    get:
      summary: Get information about cluster
      parameters:
        - name: "id"
          in: "path"
          required: true
          type: string
      responses:
        200:
          description: "Successful operation"
          schema:
            $ref: "#/definitions/Cluster"

  /clusters/{id}/nodes:
    get:
      summary: Get information about cluster nodes
      parameters:
        - name: "id"
          in: "path"
          required: true
          type: string
      responses:
        200:
          description: "Successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/ClusterNode"

  /clusters/{id}/services:
    get:
      summary: Get information about cluster services
      parameters:
        - name: "id"
          in: "path"
          required: true
          type: string
      responses:
        200:
          description: "Successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/ClusterService"
