version: '2'
services:
  etcd:
    restart: always
  api:
    image: kqueen/api:v0.11
    restart: always
    environment:
      KQUEEN_CONFIG_FILE: config/prod.py
      KQUEEN_ETCD_HOST: etcd
      KQUEEN_PROMETHEUS_WHITELIST: '172.16.238.0/24'
      # TODO: set SECRET_KEY
      KQUEEN_SECRET_KEY: ''
      BOOTSTRAP_ADMIN: 1
      BOOTSTRAP_ADMIN_USERNAME: admin
      BOOTSTRAP_ADMIN_PASSWORD: default
      BOOTSTRAP_ADMIN_ORGANIZATION: DemoOrg
      BOOTSTRAP_ADMIN_NAMESPACE: demoorg
  proxy:
    build: ./prod/nginx/
    restart: always
    ports:
      - 443:443
      - 80:80
    volumes:
      - /mnt/storage/kqueen/certs/:/mnt/letsencrypt/demo.kqueen.net/:Z
    volumes_from:
      - ui:ro
  ui:
    image: kqueen/ui:master
    environment:
      KQUEENUI_PREFERRED_URL_SCHEME: https
      KQUEEN_UI_CONFIG_FILE: config/prod.py
      KQUEENUI_KQUEEN_API_URL: http://api:5000/api/v1/
      KQUEENUI_KQUEEN_AUTH_URL: http://api:5000/api/v1/auth
      KQUEENUI_KQUEEN_SERVICE_USER_USERNAME: admin
      KQUEENUI_KQUEEN_SERVICE_USER_PASSWORD: default
      KQUEENUI_MAIL_SERVER: mail
      KQUEENUI_MAIL_PORT: 10025
      STATIC_DIR: /mnt/static/
    volumes:
      - /mnt/static/
    restart: always
  mail:
    image: modularitycontainers/postfix
    restart: always
    volumes:
      - /var/spool/postfix/
      - /var/spool/mail/
    environment:
      MYHOSTNAME: 'mail'
  prometheus:
    image: prom/prometheus
    restart: always
    ports:
      - 127.0.0.1:9090:9090
    volumes:
      - ./prod/prometheus/:/etc/prometheus/:Z
    links:
      - api
      - etcd
