version: '2'
services:
  kqueen:
    build: ./
    ports:
      - 127.0.0.1:5000:5000
    depends_on:
      - etcd
    environment:
      KQUEEN_ETCD_HOST: etcd
  kqueen_ui:
    image: atengler/kqueen-ui
    ports:
      - 127.0.0.1:5080:5080
    depends_on:
      - kqueen
    environment:
      KQUEEN_API_URL: 'http://kqueen:5000/api/v1/'
      KQUEEN_AUTH_URL: 'http://kqueen:5000/api/v1/auth'
      KQUEEN_CONFIG_FILE: 'config/prod.py'
