version: '2'
services:
  api:
    image: kqueen/api:v0.11
    ports:
      - 127.0.0.1:5000:5000
    depends_on:
      - etcd
    environment:
      KQUEEN_CONFIG_FILE: config/prod.py
      KQUEEN_ETCD_HOST: etcd
      #KQUEEN_DEBUG: 'True'
      BOOTSTRAP_ADMIN: 1
      BOOTSTRAP_ADMIN_USERNAME: admin
      BOOTSTRAP_ADMIN_PASSWORD: default
      BOOTSTRAP_ADMIN_ORGANIZATION: DemoOrg
      BOOTSTRAP_ADMIN_NAMESPACE: demoorg
    extra_hosts:
      - "ci.mcp.mirantis.net:172.16.48.254"
  ui:
    image: kqueen/ui:v0.1
    ports:
      - 127.0.0.1:5080:5080
    depends_on:
      - kqueen
    environment:
      KQUEEN_UI_CONFIG_FILE: config/prod.py
      KQUEENUI_KQUEEN_API_URL: http://api:5000/api/v1/
      KQUEENUI_KQUEEN_AUTH_URL: http://api:5000/api/v1/auth
      KQUEENUI_KQUEEN_SERVICE_USER_USERNAME: admin
      KQUEENUI_KQUEEN_SERVICE_USER_PASSWORD: default
      KQUEENUI_MAIL_SERVER: mail
      KQUEENUI_MAIL_PORT: 10025
  mail:
    image: modularitycontainers/postfix
    volumes:
      - /var/spool/postfix:/var/spool/postfix
      - /var/spool/mail:/var/spool/mail
    environment:
      MYHOSTNAME: 'mail'
