version: '2'
services:
  kqueen:
    build: ./
    ports:
      - 127.0.0.1:5000:5000
    depends_on:
      - etcd
    environment:
      KQUEEN_ETCD_HOST: etcd
      BOOTSTRAP_ADMIN: 1
      BOOTSTRAP_ADMIN_USERNAME: admin
      BOOTSTRAP_ADMIN_PASSWORD: default
      BOOTSTRAP_ADMIN_ORGANIZATION: DemoOrg
      BOOTSTRAP_ADMIN_NAMESPACE: demoorg
  kqueen_ui:
    image: atengler/kqueen-ui
    ports:
      - 127.0.0.1:5080:5080
    depends_on:
      - kqueen
    environment:
      KQUEEN_UI_CONFIG_FILE: config/prod.py
      KQUEENUI_KQUEEN_API_URL: http://kqueen:5000/api/v1/
      KQUEENUI_KQUEEN_AUTH_URL: http://kqueen:5000/api/v1/auth
      KQUEENUI_KQUEEN_SERVICE_USER_USERNAME: admin
      KQUEENUI_KQUEEN_SERVICE_USER_PASSWORD: default
