global:
  scrape_interval: '30s'

rule_files:
  - '/etc/prometheus/*.rules.yml'

scrape_configs:
  - job_name: 'kqueen'
    static_configs:
      - targets: ['api:5000']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'etcd'
    static_configs:
      - targets: ['etcd:4001']
